### ISSUE TITLE
skeleton output should normalised to lower case character.

### ISSUE THREAD

**Issue by commutecat** [rfw/confusables#3]
The skeleton module works perfectly except with one small glitch.

```
>>>from confusables import skeleton
>>>m1 = skeleton("micr0soft")
>>>m2 = skeleton("micros0ft")
>>>m1 == m2 
false
>>>m1 
'rnicrOsoft'
>>>m2 
'rnicrosOft'

#  work around 
>>>m1 = skeleton("micr0soft").lower()
>>>m2 = skeleton("micros0ft").lower()
>>>m1 == m2 
True

```

**Comment by rfw** [comment]
I think the behavior is expected – 0 and o are not confusable as defined by TR39 (e.g. rn is not confusable with M). I'm going to close this out, but if I'm misunderstanding the spec feel free to reopen.
